repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: trailing-whitespace
        # The `bumpversion` command fails to commit its own changes to
        # `.bumpversion.cfg` because it leaves some trailing whitespace.
        exclude: ^\.bumpversion\.cfg$
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.4
    hooks:
      - id: pyupgrade
        args:
          - "--py3-plus"
          - "--py36-plus"
  # Remove after upgrading to isort >=5
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/PyCQA/isort
    rev: 4.3.21-2
    hooks:
      - id: isort
        args:
          - "-sp pyproject.toml"
          - "--filter-files"
        additional_dependencies:
          - toml
        files: ".py"
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  # - repo: https://github.com/life4/flakehell
  #   rev: v.0.7.0
  #   hooks:
  #     - id: flakehell
# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v0.790
#   hooks:
#     - id: mypy
